### ISSUE TITLE
Register the project with Bower

### ISSUE THREAD

**Issue by roysanchez** [sandrocaseiro/jquery.validate.unobtrusive.bootstrap#11]
Register the project with Bower, so it can be referenced with something like:
`bower install jquery-validate-unobstrusive-bootstrap`

**Comment by mamodom** [comment]
This issue can be closed, it was resolved here 2e77558ee73f77dd4783bd169d90399b6fb85a76

**Comment by roysanchez** [comment]
Thanks!
